server:
  port: 8443
  ssl:
    key-store: classpath:keystore/baeldung.p12
    key-store-password: 627804
    keyStoreType: PKCS12
    keyAlias: baeldung
    enabled=true:
spring:
#  local DataBase
#  datasource:
#    url: jdbc:postgresql://localhost:5433/papalapa
#    username: user
#    password: secret

# Yandex Cloud DataBase
  datasource:
    url: jdbc:postgresql://rc1a-rx8wrb8e83hvov0h.mdb.yandexcloud.net:6432/papalapa-site-db?targetServerType=master&ssl=true&sslmode=verify-full
    username: user
    password: papalapa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

